In [39]:
import numpy as np
import pandas as pd
import config1

from sklearn.model_selection  import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import  mean_absolute_error ,mean_squared_error,r2_score

import warnings
warnings.filterwarnings('ignore')

import json
import pickle

In [13]:
dir(config1)

['XLSX_FILE_PATH',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'model_file_path',
 'os']

In [14]:
xlsx_file_path = config1.XLSX_FILE_PATH
df = pd.read_excel(xlsx_file_path)
df

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
0,203,2357,10,135.0,5.20,424,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10,125.0,4.00,233,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10,110.0,4.70,312,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11,118.5,4.00,233,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11,125.0,4.00,233,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,3551,4638,178.0,5.46,538,4,1.875,128.0,6.000,12.00,16.0,4080,8.4
157,1296,3211,8016,170.0,5.50,534,4,1.975,128.0,6.000,20.00,8.0,3400,7.9
158,856,3260,8809,150.0,5.50,401,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,3211,8946,170.0,5.50,534,4,1.975,128.0,6.000,20.00,8.0,3400,7.9
160,1131,2536,9807,202.0,6.00,367,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_id    161 non-null    int64
 1   Price         161 non-null    int64
 2   Sale          161 non-null    int64
 3   weight        161 non-null    float64
 4   resoloution   161 non-null    float64
 5   ppi           161 non-null    int64
 6   cpu core      161 non-null    int64
 7   cpu freq      161 non-null    float64
 8   internal mem  161 non-null    float64
 9   ram           161 non-null    float64
 10  RearCam       161 non-null    float64
 11  Front_Cam     161 non-null    float64
 12  battery       161 non-null    int64
 13  thickness     161 non-null    float64
dtypes: float64(8), int64(6)
memory usage: 17.7 KB

In [16]:
df.describe()

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,675.559006,2215.596273,621.465839,170.426087,5.209938,335.055901,4.857143,1.502832,24.501714,2.204994,10.378261,4.503106,2842.111801,8.921739
std,410.851583,768.187171,1546.618517,92.888612,1.509953,134.826659,2.444016,0.599783,28.804773,1.609831,6.181585,4.342053,1366.990838,2.192564
min,10.000000,614.000000,10.000000,66.000000,1.400000,121.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,800.000000,5.100000
25%,237.000000,1734.000000,37.000000,134.100000,4.800000,233.000000,4.000000,1.200000,8.000000,1.000000,5.000000,0.000000,2040.000000,7.600000
50%,774.000000,2258.000000,106.000000,153.000000,5.150000,294.000000,4.000000,1.400000,16.000000,2.000000,12.000000,5.000000,2800.000000,8.400000
75%,1026.000000,2744.000000,382.000000,170.000000,5.500000,428.000000,8.000000,1.875000,32.000000,3.000000,16.000000,8.000000,3240.000000,9.800000
max,1339.000000,4361.000000,9807.000000,753.000000,12.200000,806.000000,8.000000,2.700000,128.000000,6.000000,23.000000,20.000000,9500.000000,18.500000

In [17]:
df['cpu core'].value_counts()

4    81
8    52
2    14
0    10
6     2
1     2
Name: cpu core, dtype: int64

In [18]:
df1 =df.drop('Product_id',axis = 1)
df1

,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
0,2357,10,135.0,5.20,424,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,1749,10,125.0,4.00,233,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,1916,10,110.0,4.70,312,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,1315,11,118.5,4.00,233,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,1749,11,125.0,4.00,233,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,3551,4638,178.0,5.46,538,4,1.875,128.0,6.000,12.00,16.0,4080,8.4
157,3211,8016,170.0,5.50,534,4,1.975,128.0,6.000,20.00,8.0,3400,7.9
158,3260,8809,150.0,5.50,401,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,3211,8946,170.0,5.50,534,4,1.975,128.0,6.000,20.00,8.0,3400,7.9
160,2536,9807,202.0,6.00,367,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [19]:
df1.rename(columns = {'cpu core':'cpu_core','cpu freq':'cpu_freq','internal mem':'internal_mem'},inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Price         161 non-null    int64
 1   Sale          161 non-null    int64
 2   weight        161 non-null    float64
 3   resoloution   161 non-null    float64
 4   ppi           161 non-null    int64
 5   cpu_core      161 non-null    int64
 6   cpu_freq      161 non-null    float64
 7   internal_mem  161 non-null    float64
 8   ram           161 non-null    float64
 9   RearCam       161 non-null    float64
 10  Front_Cam     161 non-null    float64
 11  battery       161 non-null    int64
 12  thickness     161 non-null    float64
dtypes: float64(8), int64(5)
memory usage: 16.5 KB

In [31]:
x = df1.drop('Price',axis = 1)
y=  df1['Price']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=15)
x_train

,Sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,RearCam,Front_Cam,battery,thickness
57,57,154.0,5.00,294,4,1.000,8.000,1.000,8.0,5.0,3140,8.1
137,996,153.0,5.50,401,8,1.500,64.000,4.000,13.0,16.0,3200,7.3
55,45,174.0,5.50,178,4,1.300,4.000,0.512,5.0,0.0,2250,9.2
47,41,144.0,5.20,428,8,1.750,32.000,3.000,20.7,5.1,2930,6.9
5,12,150.0,5.50,401,4,2.300,16.000,2.000,16.0,8.0,2500,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...
156,4638,178.0,5.46,538,4,1.875,128.000,6.000,12.0,16.0,4080,8.4
128,456,753.0,12.20,247,8,1.600,32.000,3.000,8.0,2.0,9500,8.0
119,378,118.0,4.00,245,4,1.200,4.000,0.512,5.0,2.0,1730,10.9
133,599,112.0,5.00,294,8,1.400,8.000,1.000,8.0,8.0,1900,6.3
140,1224,102.9,2.20,128,0,0.000,0.256,0.128,1.3,0.0,950,18.5

In [32]:
lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)

LinearRegression()

In [33]:
y_pred_train = lin_reg.predict(x_train)

mse = mean_squared_error(y_train, y_pred_train)
print("Mean Squared Error :",mse)

rmse = np.sqrt(mse)
print("Root Mean Squared Error :",rmse)

mae = mean_absolute_error(y_train, y_pred_train)
print("Mean Absolute Error :",mae)

r_squared = r2_score(y_train, y_pred_train)
print("R Squared Value is :",r_squared)

Mean Squared Error : 27825.31461287338
Root Mean Squared Error : 166.80921621083584
Mean Absolute Error : 137.39930429051267
R Squared Value is : 0.9533317918456904

In [34]:
y_pred_test = lin_reg.predict(x_test)
mse = mean_squared_error(y_test, y_pred_test)
print("Mean Squared Error :",mse)

rmse = np.sqrt(mse)
print("Root Mean Squared Error :",rmse)

mae = mean_absolute_error(y_test, y_pred_test)
print("Mean Absolute Error :",mae)

r_squared = r2_score(y_test, y_pred_test)
print("R Squared Value is :",r_squared)

Mean Squared Error : 25256.56562843022
Root Mean Squared Error : 158.9231437784636
Mean Absolute Error : 135.19969481210842
R Squared Value is : 0.9516554254110932

In [35]:
project_data = {'columns': x.columns.tolist()}
project_data

{'columns': ['Sale',
  'weight',
  'resoloution',
  'ppi',
  'cpu_core',
  'cpu_freq',
  'internal_mem',
  'ram',
  'RearCam',
  'Front_Cam',
  'battery',
  'thickness']}

In [36]:
 with open('project_data.json','w') as f:
    json.dump(project_data,f)

In [37]:
x.head(1).T

                    0
Sale            10.00
weight         135.00
resoloution      5.20
ppi            424.00
cpu_core         8.00
cpu_freq         1.35
internal_mem    16.00
ram              3.00
RearCam         13.00
Front_Cam        8.00
battery       2610.00
thickness        7.40

In [38]:
Sale            = 9
weight          = 130
resoloution     = 6.20
ppi             = 400
cpu_core        = 4
cpu_freq       = 2.35
internal_mem   = 32
ram             = 8
RearCam         = 16
Front_Cam       = 12
battery        = 4610
thickness      = 8.40

test_array= np.array([Sale,weight,resoloution,ppi,cpu_core,cpu_freq,internal_mem,ram,RearCam,Front_Cam,battery,thickness])
           
print(test_array)

predicted_price = np.around(lin_reg.predict([test_array])[0],3)
print('predicted_price:',predicted_price)

[9.00e+00 1.30e+02 6.20e+00 4.00e+02 4.00e+00 2.35e+00 3.20e+01 8.00e+00
 1.60e+01 1.20e+01 4.61e+03 8.40e+00]
predicted_price: 3229.714

In [40]:
with open('cellphone_model.pkl','wb') as f:
    pickle.dump(lin_reg,f)